# Disallowing packages: openvpn
# If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process
#addons:
#    apt:
#        sources:
#            - ubuntu-toolchain-r-test
#        packages:
#            - openvpn

services:
    - docker

before_install:
    - docker --version

install:
    - git clone https://github.com/docker-library/official-images.git official-images

# Assist with ci test debugging:
#   - DEBUG=1
before_script:
    - image="elie195/openvpn"
    - docker build -t "$image" .
    - docker inspect "$image"
    - docker run --rm "$image" openvpn --version || true # why does it return 1?
    - docker run --rm "$image" openssl version

script:
    - official-images/test/run.sh "$image"
    - test/run.sh "$image"

after_script:
    - docker images

notifications:
  slack:
    secure: vHjwFy7hwRBvpqzEw8+9P6SXSw+/Gf/CriA61ZV3b61cB/POFTiKsPe2T9O2+3dF2LyzySPgAw8K2FUC1r36QldXTSFfG2I6BRGsayGwTVbrSACAVRM8Wch4ScLBfTKQHmeSd6dk6eMMkqEj0V6HtLWK/CeU1GwzL3WK67UFbLo//j+E4bEQ2g/CDeTlmYKzdmqT04e7SLvN5FOKXmKb/CBQfN+dwqeb+dgdimcMGCo2fUY/8IIWcmERo7OucosLamR+Gv8yUgSrcLmkp0Y7b/mcKFU9q+tJaMVzbzlzMvtHUQd0jU7RjFrr7NZa29mzEGIiWlfhuXN6c8rGQLDFtkNimghAgHILAvk7E853FGXnWoX9YE2QCpbu5vcU3FFysv/y1FzVzKnpfw/1dfRQ4OWVwumXPH10g6Znn8viyM+OXdAnSNiO0UCUFe2GVUJULQpnYe/m7xVt8UBPYIrdrVsPQnq1gB/1c6h/y5S2HNpLxCEYI3LGjsru+URA1bdnoy+SlSxe7mDORcIv1wWmXYMPWrXzYBFiVTc0fWPNzVyLNkqEOFiCs3Iss+b6qXrs/CJkueuQa01w4pdLP8RK/yDAL9qsOhnAmYBa2FoKw3B5LjDwNuO7b744UBNNUNbbZ4+G9kCEt2rJeX68ZtHrOd55MILCaH6320MSkY/bhIo=
